apiVersion: v1
kind: Service
metadata:
  name: k8s-web-to-ngnix
spec:
  selector:
    app: k8s-web-to-ngnix
  ports:
  - port: 3333
    targetPort: 3000
  type: LoadBalancer
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: k8s-web-to-ngnix
spec:
  selector:
    matchLabels:
      app: k8s-web-to-ngnix
  template:
    metadata:
      labels:
        app: k8s-web-to-ngnix
    spec:
      containers:
      - name: k8s-web-to-ngnix
        image: hashtag1229/k8s-web-to-ngnix
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m" #half of a  cpu core
        ports:
        - containerPort: 3000
  replicas: 3